name: kohi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  freezed_annotation: ^3.1.0
  dotenv: ^4.2.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^7.0.0
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
